---

- name: Setup Kubeadm Playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Add Kubernetes repo
      yum_repository:
       name: kubernetes
       baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
       file: kubernetes
       enabled: yes
       gpgcheck: yes
       repo_gpgcheck: yes
       gpgkey: 'https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'
       description: kube-repo
    - name: Disable SELinux
      selinux:
        state: disabled
      register: sel
    - name: Reboot for SELinux
      reboot:
        msg: "Rebooted by ansible"
        reboot_timeout: 300
      when: sel.changed
    - name: Install Packages
      package:
        name: "{{ item }}"
        state: installed
      loop:
        - podman
        - kubelet
        - kubeadm
        - kubectl

- name: Start Kubelet
  hosts: kube-masters,kube-nodes
  gather_facts: false
  tasks:
    - name: Start Kubelet
      service:
        name: kubelet
        state: started
        enabled: true
      
